### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by UsamaMehboob** [twister2016/twister#55]
I was trying to build twister on my machine, my nics were alredy boun. running make install gave me this error
cp twister/include/*.h /home/twister/include
cp dpdk/i686-native-linuxapp-gcc/include/*.h /home/twister/include
cp dpdk/i686-native-linuxapp-gcc/include/generic/*.h /home/twister/include/generic/
cp dpdk/i686-native-linuxapp-gcc/include/exec-env/*.h /home/twister/include/exec-env/
./post-install
Module already inserted
These devices are already binded 
['0000:00:08.0', '0000:00:09.0']
blacklist  ['eth0']
whitelist ['eth1']
Traceback (most recent call last):
  File "/home/twister/config/tw_config.py", line 101, in <module>
    coremask, portmask, blacklist = parse_twister_params(twister_conf)
  File "/home/twister/config/tw_config.py", line 72, in parse_twister_params
    sys_tree = populate_lshw_paramas()
  File "/home/twister/config/tw_config.py", line 22, in populate_lshw_paramas
    tempdic["logicalname"]=pcichild["logicalname"]
KeyError: 'logicalname'
make: *** [install] Error 1

**Comment by wriaz** [comment]
[This commit](https://github.com/twister2016/twister/commit/728037c384f22e1e1fb3dcfd9a928e992f481683) resloves the issue

**Comment by UsamaMehboob** [comment]
I compiled this and again got this error
./post-install
Inserting Modules in kernel
Traceback (most recent call last):
  File "/home/twister/config/tw_config.py", line 195, in <module>
    main()
  File "/home/twister/config/tw_config.py", line 170, in main
    coremask = get_coremask(config)
  File "/home/twister/config/tw_config.py", line 103, in get_coremask
    total_cpus = get_total_cpus()
  File "/home/twister/config/tw_config.py", line 81, in get_total_cpus
    total_cpus = int(out.split()[11]) -1
ValueError: invalid literal for int() with base 10: 'On-line'
make: *** [install] Error 1
